modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_source_url}/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="${mod_source_url}"
logoFile="logo.png"
credits="${mod_credits}"
authors="${mod_author}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

# Required Dependencies
[[dependencies.${mod_id}]]
    modId="neoforge"
    versionRange="[${neo_version},)"
[[dependencies.${mod_id}]]
    modId="minecraft"
    versionRange="${minecraft_version_range}"
[[dependencies."${mod_id}"]]
    modId = "kubejs"
    versionRange = "[${kubejs_version},)"
    ordering = "AFTER"

## Optional Dependencies
[[dependencies."${mod_id}"]]
    modId = "kaleidoscope_cookery"
    type = "optional"
    versionRange = "[${cookery_version},)"
    ordering = "AFTER"
[[dependencies."${mod_id}"]]
    modId = "kaleidoscope_tavern"
    type = "optional"
    versionRange = "[${tavern_version},)"
    ordering = "AFTER"
[[dependencies."${mod_id}"]]
    modId = "kaleidoscope_nether"
    type = "optional"
    versionRange = "[${nether_version},)"
    ordering = "AFTER"
[[dependencies."${mod_id}"]]
    modId = "kaleidoscope_end"
    type = "optional"
    versionRange = "[${end_version},)"
    ordering = "AFTER"
[[dependencies."${mod_id}"]]
    modId = "kaleidoscope_chinese_food"
    type = "optional"
    versionRange = "[${chinese_food_version},)"
    ordering = "AFTER"